#!/bin/bash
#PBS -l nodes=1:ppn=8,vmem=8gb,walltime=0:05:00
#PBS -N acpcART
#PBS -V

#TODO This app uses /N/u/brlife/git/acpcdetect locally installed. 

module load freesurfer

set -e

export input_t1=$(jq -r .t1 config.json)
cp $input_t1 t1.nii.gz

time singularity exec -e docker://brainlife/fsl:5.0.9 ./fsl.sh

gunzip t1.nii.gz
datatype=`mri_info t1.nii --type`
if [ $datatype != "uchar" ]; then
    echo "converting datatype to uchar"
    mri_convert -i t1.nii -odt uchar -o t1.nii
fi

#do acpcdetect
export ARTHOME=/N/u/brlife/git/acpcdetect
$ARTHOME/acpcdetect -v -i t1.nii -o t1.aligned.nii 

echo "converting datatype to float"
mri_convert -i t1.aligned.nii -odt float -o t1.nii

gzip t1.nii

		
