#!/bin/bash
#PBS -l nodes=1:ppn=8:dc2,walltime=0:05:00
#PBS -N acpcART
#PBS -V

if [ $ENV == "IUHPC" ]; then
	cd $PBS_O_WORKDIR
	module load freesurfer
fi

export ARTHOME=/N/u/brlife/git/acpcdetect

export input_t1=$(jq -r .t1 config.json)

cp $input_t1 .
gunzip t1.nii.gz

datatype=`$mri_info t1.nii --type`
if [ $datatype == "uchar" ]; then
   echo "doing acpc alignment" 
   $ARTHOME/acpcdetect -v -i t1.nii -o t1.nii
else
	echo "converting datatype to uchar"
	mri_convert -i t1.nii -odt uchar -o t1.nii
	echo "doing acpc alignment"
	$ARTHOME/acpcdetect -v -i t1.nii -o t1.nii
fi

gzip t1.nii

if [ -s t1_ACPC.txt ]
then 
     echo 0 > finished
else
	echo "ACPC failed"
	echo 1 > finished
	exit 1
fi		