#!/bin/bash
#PBS -l nodes=1:ppn=8,vmem=8gb,walltime=0:05:00
#PBS -N acpcART
#PBS -V

if [ $ENV == "IUHPC" ]; then
	cd $PBS_O_WORKDIR
	module load freesurfer
	module load fsl
fi

export ARTHOME=/N/u/brlife/git/acpcdetect

export input_t1=$(jq -r .t1 config.json)

cp $input_t1 .

if [ $(jq -r .crop_reorient config.json) == true ]; then
	echo "reorienting and cropping"
	fslreorient2std t1.nii.gz t1.nii.gz
	robustfov -i t1.nii.gz -r t1.nii.gz
fi

gunzip t1.nii.gz

datatype=`$mri_info t1.nii --type`
if [ $datatype == "uchar" ]; then
   echo "doing acpc alignment" 
   $ARTHOME/acpcdetect -v -i t1.nii -o t1.nii -sform 
else
	echo "converting datatype to uchar"
	mri_convert -i t1.nii -odt uchar -o t1.nii
	echo "doing acpc alignment"
	$ARTHOME/acpcdetect -v -i t1.nii -o t1.nii -sform 
fi

mri_convert -i t1.nii -odt float -o t1.nii
echo "out data type:"
mri_info t1.nii --type

gzip t1.nii


		
